# Step 1: Use Node.js base image
FROM node:20 AS build

# Step 2: Set working directory
WORKDIR /app

# Step 3: Copy package files and install dependencies
COPY package*.json yarn.lock ./

# Install Yarn globally (명시적으로 설치)
#RUN npm install -g yarn

# Install dependencies
RUN yarn install

# Step 4: Copy source files and build the app
COPY . .
# RUN yarn build

CMD ["yarn", "dev"]

EXPOSE 5173